### ISSUE TITLE
Error: volkswagencarnet.vw_timer.BasicSettings() argument after ** must be a mapping, not NoneType

### ISSUE THREAD

**Issue by birgersp** [robinostlund/volkswagencarnet#185] opened 2022-03-24 19:44 UTC
Hey,

I updated this package to v4.4.53, and then my vehicle status requests fail with this error message:

> volkswagencarnet.vw_timer.BasicSettings() argument after ** must be a mapping, not NoneType

I'll investigate some more when I have time, now I just had to downgrade to 4.4.48, which is what I had before. Then the error is gone.

**Comment by milkboy** [comment] 2022-04-10 08:42
Mind sharing some information about your car (model, year, engine)?
Anyway, according to my best guess from the error above, could you try [v4.4.54 beta 1](https://github.com/robinostlund/volkswagencarnet/releases/tag/v4.4.54-beta1) ?

**Comment by milkboy** [comment] 2022-04-11 09:24
Or see if the problem is fixed in https://github.com/robinostlund/volkswagencarnet/releases/tag/v4.4.54 ? If not, a little bit more context (stack trace, api responses) might be needed to figure it out

**Closed** 2023-12-18 10:09 UTC
